<?php

/**
 * @file
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_page_attachments_alter().
 */
function fitfirst_page_attachments_alter(array &$attachments) {
  if (Settings::get('debug_browsersync')) {
    $attachments['#attached']['library'][] = 'fitfirst/debug__browsersync';
  }

  if (Settings::get('debug_layout')) {
    $attachments['#attached']['library'][] = 'fitfirst/debug__layout';
  }
}